-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 14:28:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedor`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `NombreFoto` VARCHAR(20) NOT NULL,
  `PrecioVenta` FLOAT NOT NULL,
  `Existencias` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Compra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `idCompra` VARCHAR(20) NOT NULL,
  `Proveedor` VARCHAR(20) NOT NULL,
  `Fecha` DATE NOT NULL,
  `ValorTotal` FLOAT NOT NULL,
  `SaldoRestante` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_Compra_Proveedor1_idx` (`Proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_HacerCompra`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idCliente` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(10) NULL,
  `NombreFoto` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(15) NULL,
  `Direccion` VARCHAR(45) NULL,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Privilegios` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `idVenta` VARCHAR(20) NOT NULL,
  `Cliente` VARCHAR(20) NOT NULL,
  `Fecha` DATE 	NOT NULL,
  `ValorTotal` FLOAT NOT NULL,
  `SaldoRestante` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Cliente1_idx` (`Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Se_Hizo_A_Cliente`
    FOREIGN KEY (`Cliente`)
    REFERENCES `mydb`.`Usuario` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductoDelProveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProductoDelProveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProductoDelProveedor` (
  `Proveedor` VARCHAR(20) NOT NULL,
  `Producto` VARCHAR(20) NOT NULL,
  `PrecioCompra` FLOAT NOT NULL,
  PRIMARY KEY (`Proveedor`, `Producto`),
  INDEX `fk_Proveedor_has_Producto_Producto1_idx` (`Producto` ASC) VISIBLE,
  INDEX `fk_Proveedor_has_Producto_Proveedor_idx` (`Proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_SuministrarProductos`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SerSuministrado`
    FOREIGN KEY (`Producto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductoDeCompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProductoDeCompra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProductoDeCompra` (
  `Compra` VARCHAR(20) NOT NULL,
  `Producto` VARCHAR(20) NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`Compra`, `Producto`),
  INDEX `fk_Compra_has_Producto_Compra1_idx` (`Compra` ASC) VISIBLE,
  INDEX `fk_ProductoDeCompra_Producto1_idx` (`Producto` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Tiene_Articulos`
    FOREIGN KEY (`Compra`)
    REFERENCES `mydb`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Fue_Comprado`
    FOREIGN KEY (`Producto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductoDelCliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProductoDelCliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProductoDelCliente` (
  `Cliente` VARCHAR(20) NOT NULL,
  `Producto` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Cliente`, `Producto`),
  INDEX `fk_Cliente_has_Producto_Producto1_idx` (`Producto` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Producto_Cliente1_idx` (`Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Ha_Comprado`
    FOREIGN KEY (`Cliente`)
    REFERENCES `mydb`.`Usuario` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Ha_Sido_Vendido`
    FOREIGN KEY (`Producto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductoDeVenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProductoDeVenta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProductoDeVenta` (
  `Venta` VARCHAR(20) NOT NULL,
  `Producto` VARCHAR(20) NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`Venta`, `Producto`),
  INDEX `fk_Venta_has_Producto_Producto1_idx` (`Producto` ASC) VISIBLE,
  INDEX `fk_Venta_has_Producto_Venta1_idx` (`Venta` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Tiene_Productos`
    FOREIGN KEY (`Venta`)
    REFERENCES `mydb`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Fue_Vendido`
    FOREIGN KEY (`Producto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
