-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 15:59:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema tiendaBases
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tiendaBases` ;

-- -----------------------------------------------------
-- Schema tiendaBases
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendaBases` DEFAULT CHARACTER SET utf8 ;
USE `tiendaBases` ;

-- -----------------------------------------------------
-- Table `tiendaBases`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiendaBases`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `tiendaBases`.`Proveedor` (
  `idProveedor` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedor`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaBases`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiendaBases`.`Producto` ;

CREATE TABLE IF NOT EXISTS `tiendaBases`.`Producto` (
  `idProducto` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `NombreFoto` VARCHAR(20) NOT NULL,
  `PrecioVenta` INT NOT NULL,
  `Existencias` INT NOT NULL DEFAULT 0,
  `PrecioCompra` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaBases`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiendaBases`.`Compra` ;

CREATE TABLE IF NOT EXISTS `tiendaBases`.`Compra` (
  `idCompra` VARCHAR(20) NOT NULL,
  `Fecha` DATE NOT NULL,
  `ValorTotal` INT NOT NULL,
  `SaldoRestante` INT NULL DEFAULT 0,
  PRIMARY KEY (`idCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaBases`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiendaBases`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `tiendaBases`.`Usuario` (
  `idUsuario` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(10) NULL,
  `NombreFoto` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(15) NULL,
  `Direccion` VARCHAR(45) NULL,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `Passw` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaBases`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiendaBases`.`Venta` ;

CREATE TABLE IF NOT EXISTS `tiendaBases`.`Venta` (
  `idVenta` VARCHAR(20) NOT NULL,
  `Cliente` VARCHAR(20) NOT NULL,
  `Fecha` DATE NOT NULL,
  `ValorTotal` INT NOT NULL,
  `SaldoRestante` INT NULL DEFAULT 0,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Cliente1_idx` (`Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Se_Hizo_A_Cliente`
    FOREIGN KEY (`Cliente`)
    REFERENCES `tiendaBases`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaBases`.`ProductoDelProveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiendaBases`.`ProductoDelProveedor` ;

CREATE TABLE IF NOT EXISTS `tiendaBases`.`ProductoDelProveedor` (
  `Proveedor` VARCHAR(20) NOT NULL,
  `Producto` VARCHAR(20) NOT NULL,
  `IdPDP` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`IdPDP`),
  INDEX `fk_Proveedor_has_Producto_Producto1_idx` (`Producto` ASC) VISIBLE,
  INDEX `fk_Proveedor_has_Producto_Proveedor_idx` (`Proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_SuministrarProductos`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `tiendaBases`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SerSuministrado`
    FOREIGN KEY (`Producto`)
    REFERENCES `tiendaBases`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaBases`.`ProductoDeCompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiendaBases`.`ProductoDeCompra` ;

CREATE TABLE IF NOT EXISTS `tiendaBases`.`ProductoDeCompra` (
  `Compra` VARCHAR(20) NOT NULL,
  `Cantidad` INT NOT NULL,
  `Producto` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Compra`, `Producto`),
  INDEX `fk_Compra_has_Producto_Compra1_idx` (`Compra` ASC) VISIBLE,
  INDEX `fk_ProductoDeCompra_Producto1_idx` (`Producto` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Tiene_Articulos`
    FOREIGN KEY (`Compra`)
    REFERENCES `tiendaBases`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductoDeCompra_Producto1`
    FOREIGN KEY (`Producto`)
    REFERENCES `tiendaBases`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaBases`.`ProductoDelCliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiendaBases`.`ProductoDelCliente` ;

CREATE TABLE IF NOT EXISTS `tiendaBases`.`ProductoDelCliente` (
  `Cliente` VARCHAR(20) NOT NULL,
  `Producto` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Cliente`, `Producto`),
  INDEX `fk_Cliente_has_Producto_Producto1_idx` (`Producto` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Producto_Cliente1_idx` (`Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Ha_Comprado`
    FOREIGN KEY (`Cliente`)
    REFERENCES `tiendaBases`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Ha_Sido_Vendido`
    FOREIGN KEY (`Producto`)
    REFERENCES `tiendaBases`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaBases`.`ProductoDeVenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiendaBases`.`ProductoDeVenta` ;

CREATE TABLE IF NOT EXISTS `tiendaBases`.`ProductoDeVenta` (
  `Venta` VARCHAR(20) NOT NULL,
  `Producto` VARCHAR(20) NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`Venta`, `Producto`),
  INDEX `fk_Venta_has_Producto_Producto1_idx` (`Producto` ASC) VISIBLE,
  INDEX `fk_Venta_has_Producto_Venta1_idx` (`Venta` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Tiene_Productos`
    FOREIGN KEY (`Venta`)
    REFERENCES `tiendaBases`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Fue_Vendido`
    FOREIGN KEY (`Producto`)
    REFERENCES `tiendaBases`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
